// Code generated by mdatagen. DO NOT EDIT.

package natsreceiver

import (
	"go.uber.org/goleak"
	"testing"
)

func TestMain(m *testing.M) {
	goleak.VerifyTestMain(m, goleak.IgnoreAnyFunction("github.com/nats-io/nats.go/(*Conn).doReconnect"))
}
